version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass royston1
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'